import pandas as pd
import datetime
from elasticsearch import Elasticsearch

# Password for the 'elastic' user generated by Elasticsearch
ELASTIC_PASSWORD = "bovB1xg-SzKotDsmn9B+"

# Create the client instance
client = Elasticsearch(
    "https://localhost:9200",
    ca_certs="./http_ca.crt",
    basic_auth=("elastic", ELASTIC_PASSWORD)
)

# 读取 CSV 文件
df = pd.read_csv('Notice.csv')

# 将数据添加到 Elasticsearch 索引
# 这里假设您已经创建了 Elasticsearch 索引，例如名为 "notices"
# 您可以根据需要调整索引名称和字段映射


for _, row in df.iterrows():
    # row["notice_text"] = row["notice_text"].strip('\"')
    notice_data = {
        "notice_catalog": str(row["notice_catalog"]),
        "notice_creator": str(row["notice_creator"]),
        "notice_link": str(row["notice_link"]),
        "notice_department": str(row["notice_source"]),
        "notice_text": str(row["notice_text"]),
        "notice_time": datetime.datetime.strptime(row["notice_time"], "%Y-%m-%d %H:%M:%S"),
        "notice_title": str(row["notice_title"]),
    }
    # 将 notice_data 添加到 Elasticsearch 索引
    # 例如使用 Elasticsearch Python 客户端进行操作
    client.index(index="notices", body=notice_data)

# row_index 存储了每一行的索引
row_index = df.index.tolist()

# 打印示例索引
print(row_index)

# 清除 Elasticsearch 索引
# 例如使用 Elasticsearch Python 客户端进行操作
# client.indices.delete(index="notices")
